// This file is automatically generated from pg-client.ts
// JavaScript version for compatibility with CommonJS imports

const { Pool } = require("pg");

// Create a PostgreSQL connection pool
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  max: 20,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 2000,
});

// Test the connection
pool.query("SELECT NOW()", (err, res) => {
  if (err) {
    console.error("Error connecting to PostgreSQL:", err);
  } else {
    console.log("PostgreSQL connected:", res.rows[0].now);
  }
});

// Helper function for executing queries
async function executeQuery(text, params) {
  try {
    const start = Date.now();
    const res = await pool.query(text, params);
    const duration = Date.now() - start;

    if (process.env.NODE_ENV === "development") {
      console.log("Executed query", { text, duration, rows: res.rowCount });
    }

    return res;
  } catch (error) {
    console.error("Error executing query:", error);
    throw error;
  }
}

// Helper function for transactions
async function transaction(callback) {
  const client = await pool.connect();

  try {
    await client.query("BEGIN");
    const result = await callback(client);
    await client.query("COMMIT");
    return result;
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

// Clean up on application shutdown
process.on("SIGINT", async () => {
  await pool.end();
  process.exit(0);
});

// Add these as methods to the exported object for CommonJS compatibility
pool.executeQuery = executeQuery;
pool.transaction = transaction;

module.exports = pool;
